// Package security 提供平台模块共享的底层安全原语。
package security

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io"

	"github.com/J-S-Te/Basic-Platform/internal/shared/sm3"
)

// CustomerRefProtector 保护"平台身份 ↔ CRM 客户标识"绑定：
//   - Encrypt/Decrypt 使用 AES-256-GCM，密文仅用于 authorization-context 服务端受控下发；
//   - Digest 使用 HMAC-SM3 键控摘要，供查重与唯一约束，域分隔输入由调用方拼接。
//
// 两个密钥独立配置（IAM_CUSTOMER_REF_ENCRYPTION_KEY / IAM_CUSTOMER_REF_DIGEST_KEY）。
// 未配置时所有操作失败关闭，绝不以明文或非键控摘要降级：绑定一旦失去保护就无法安全重建。
type CustomerRefProtector struct {
	aesKey    []byte
	digestKey []byte
}

// NewCustomerRefProtector 接受 Base64 编码的 32 字节密钥。开发环境可不配置以便启动，
// 但绑定写入与解析会明确失败，绝不以明文作为降级路径。
func NewCustomerRefProtector(encryptionKeyBase64, digestKeyBase64 string) (*CustomerRefProtector, error) {
	protector := &CustomerRefProtector{}
	if encryptionKeyBase64 != "" {
		key, err := base64.StdEncoding.DecodeString(encryptionKeyBase64)
		if err != nil {
			return nil, fmt.Errorf("decode IAM_CUSTOMER_REF_ENCRYPTION_KEY: %w", err)
		}
		if len(key) != 32 {
			return nil, errors.New("IAM_CUSTOMER_REF_ENCRYPTION_KEY must decode to 32 bytes")
		}
		protector.aesKey = append([]byte(nil), key...)
	}
	if digestKeyBase64 != "" {
		key, err := base64.StdEncoding.DecodeString(digestKeyBase64)
		if err != nil {
			return nil, fmt.Errorf("decode IAM_CUSTOMER_REF_DIGEST_KEY: %w", err)
		}
		if len(key) != 32 {
			return nil, errors.New("IAM_CUSTOMER_REF_DIGEST_KEY must decode to 32 bytes")
		}
		protector.digestKey = append([]byte(nil), key...)
	}
	return protector, nil
}

// Encrypt encrypts a canonical customer reference for storage.
func (protector *CustomerRefProtector) Encrypt(value string) ([]byte, error) {
	gcm, err := protector.gcm()
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("generate customer ref encryption nonce: %w", err)
	}
	return gcm.Seal(nonce, nonce, []byte(value), nil), nil
}

// Decrypt reads a ciphertext generated by Encrypt.
func (protector *CustomerRefProtector) Decrypt(ciphertext []byte) (string, error) {
	gcm, err := protector.gcm()
	if err != nil {
		return "", err
	}
	if len(ciphertext) < gcm.NonceSize() {
		return "", errors.New("customer ref ciphertext is malformed")
	}
	plaintext, err := gcm.Open(nil, ciphertext[:gcm.NonceSize()], ciphertext[gcm.NonceSize():], nil)
	if err != nil {
		return "", fmt.Errorf("decrypt customer ref ciphertext: %w", err)
	}
	return string(plaintext), nil
}

// Digest 返回键控 HMAC-SM3 摘要。与手机号保护不同，这里没有非键控降级路径：
// 低熵的数字型 customer_id 一旦以普通摘要入库，数据库泄露者即可离线字典重建。
func (protector *CustomerRefProtector) Digest(value string) ([]byte, error) {
	if protector == nil || len(protector.digestKey) != 32 {
		return nil, errors.New("customer ref digest key is not configured")
	}
	mac := hmac.New(sm3.New, protector.digestKey)
	_, _ = mac.Write([]byte(value))
	return mac.Sum(nil), nil
}

func (protector *CustomerRefProtector) gcm() (cipher.AEAD, error) {
	if protector == nil || len(protector.aesKey) != 32 {
		return nil, errors.New("customer ref encryption is not configured")
	}
	block, err := aes.NewCipher(protector.aesKey)
	if err != nil {
		return nil, fmt.Errorf("create customer ref cipher: %w", err)
	}
	return cipher.NewGCM(block)
}
