CREATE TABLE IF NOT EXISTS iam_personnel_change_request (
  id CHAR(26) NOT NULL,
  tenant_id CHAR(26) NOT NULL,
  user_id CHAR(26) NOT NULL,
  source_membership_id CHAR(26) NULL,
  target_org_unit_id CHAR(26) NULL,
  target_position_id CHAR(26) NULL,
  change_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  reason VARCHAR(500) NOT NULL,
  approval_reference VARCHAR(128) NULL,
  effective_at DATETIME(3) NOT NULL,
  submitted_by CHAR(26) NOT NULL,
  approved_by CHAR(26) NULL,
  approved_at DATETIME(3) NULL,
  executed_at DATETIME(3) NULL,
  cancelled_at DATETIME(3) NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_personnel_change_tenant_status_effective (tenant_id, status, effective_at),
  KEY idx_personnel_change_user (tenant_id, user_id, created_at),
  CONSTRAINT chk_personnel_change_type CHECK (change_type IN ('PROMOTION','DEMOTION','TRANSFER','TERMINATION','REHIRE')),
  CONSTRAINT chk_personnel_change_status CHECK (status IN ('DRAFT','PENDING_APPROVAL','PENDING_HANDOVER','SCHEDULED','EXECUTED','REJECTED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
