CREATE TABLE IF NOT EXISTS iam_org_unit (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    parent_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(128) NOT NULL,
    org_type VARCHAR(32) NOT NULL,
    path VARCHAR(2048) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    depth INT UNSIGNED NOT NULL,
    leader_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_org_code (tenant_id, code),
    KEY idx_org_parent (tenant_id, parent_id, status),
    KEY idx_org_path (tenant_id, path(191)),
    CONSTRAINT fk_org_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_org_parent FOREIGN KEY (parent_id) REFERENCES iam_org_unit (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS iam_position (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    org_unit_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(128) NOT NULL,
    position_level VARCHAR(32) NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_position_code (tenant_id, org_unit_id, code),
    KEY idx_position_org (tenant_id, org_unit_id, status),
    CONSTRAINT fk_position_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_position_org FOREIGN KEY (org_unit_id) REFERENCES iam_org_unit (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS iam_membership (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    org_unit_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    position_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    membership_type VARCHAR(32) NOT NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    valid_from DATETIME(3) NULL,
    valid_until DATETIME(3) NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_membership (tenant_id, user_id, org_unit_id, position_id, membership_type),
    KEY idx_membership_user (tenant_id, user_id, status),
    KEY idx_membership_org (tenant_id, org_unit_id, status),
    CONSTRAINT fk_membership_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES iam_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_membership_org FOREIGN KEY (org_unit_id) REFERENCES iam_org_unit (id) ON DELETE RESTRICT,
    CONSTRAINT fk_membership_position FOREIGN KEY (position_id) REFERENCES iam_position (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
