-- Stores the file object generated by an asynchronous export job.
-- No GORM AutoMigrate is used by this project.
ALTER TABLE async_job
    ADD COLUMN result_file_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL AFTER last_error_message,
    ADD KEY idx_async_job_result_file (result_file_id),
    ADD CONSTRAINT fk_async_job_result_file FOREIGN KEY (result_file_id) REFERENCES file_object (id) ON DELETE RESTRICT;
