CREATE TABLE IF NOT EXISTS file_object (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    application_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    original_name VARCHAR(512) NOT NULL,
    file_extension VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    media_type VARCHAR(255) NULL,
    classification VARCHAR(32) NOT NULL,
    owner_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    owner_org_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    current_version_no INT UNSIGNED NOT NULL DEFAULT 0,
    current_version_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PRIMARY KEY (id),
    KEY idx_file_app_time (tenant_id, application_id, created_at),
    KEY idx_file_owner (tenant_id, owner_user_id, created_at),
    CONSTRAINT fk_file_object_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_file_object_application FOREIGN KEY (application_id) REFERENCES platform_application (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS file_version (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    file_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    version_no INT UNSIGNED NOT NULL,
    storage_relative_path VARCHAR(1000) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    sha256 BINARY(32) NOT NULL,
    media_type VARCHAR(255) NULL,
    original_name VARCHAR(512) NOT NULL,
    uploader_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    upload_request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_file_version (file_id, version_no),
    UNIQUE KEY uk_file_storage_path (storage_relative_path),
    CONSTRAINT fk_file_version_file FOREIGN KEY (file_id) REFERENCES file_object (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS file_binding (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    application_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    file_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    resource_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    resource_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    binding_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    display_name VARCHAR(512) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_file_binding (application_id, resource_type, resource_id, file_id, binding_type),
    KEY idx_file_binding_resource (tenant_id, application_id, resource_type, resource_id, status),
    CONSTRAINT fk_file_binding_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_file_binding_application FOREIGN KEY (application_id) REFERENCES platform_application (id) ON DELETE RESTRICT,
    CONSTRAINT fk_file_binding_file FOREIGN KEY (file_id) REFERENCES file_object (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
