CREATE TABLE IF NOT EXISTS subsystem_service_instance (
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    application_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    environment_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    application_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    environment_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    service_name VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    service_role VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    protocol VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'http',
    internal_host VARCHAR(255) NOT NULL,
    internal_port INT UNSIGNED NOT NULL,
    path_prefix VARCHAR(255) NOT NULL DEFAULT '',
    health_endpoint VARCHAR(255) NOT NULL DEFAULT '',
    version VARCHAR(128) NOT NULL DEFAULT '',
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'DISCOVERED',
    last_seen_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (tenant_id, environment_id, service_name, service_role),
    KEY idx_subsystem_service_health (tenant_id, application_code, environment_code, status, last_seen_at),
    CONSTRAINT fk_subsystem_service_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_subsystem_service_application FOREIGN KEY (application_id) REFERENCES platform_application (id) ON DELETE RESTRICT,
    CONSTRAINT fk_subsystem_service_environment FOREIGN KEY (environment_id) REFERENCES platform_application_environment (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
