-- 000045 historically registered contract_management/dev as an ACTIVE demonstration
-- environment. Production delivery selection is image/package driven, so that seed made a
-- system which was not shipped look deployed. Historical migrations are immutable: retire the
-- seed here and physically remove it only when no runtime, security, configuration or audit
-- evidence references it.

UPDATE platform_application_login_target AS target
JOIN platform_application_environment AS environment
  ON environment.id = target.environment_id
 AND environment.tenant_id = target.tenant_id
 AND environment.application_id = target.application_id
JOIN platform_application AS application
  ON application.id = environment.application_id
 AND application.tenant_id = environment.tenant_id
SET target.status = 'DISABLED',
    target.version = target.version + 1,
    target.updated_at = UTC_TIMESTAMP(3)
WHERE application.code = 'contract_management'
  AND environment.id = '01J00000000000000000000301'
  AND environment.environment = 'dev'
  AND target.id = '01J00000000000000000000302'
  AND target.status <> 'DISABLED';

UPDATE platform_application_environment AS environment
JOIN platform_application AS application
  ON application.id = environment.application_id
 AND application.tenant_id = environment.tenant_id
SET environment.status = 'DISABLED',
    environment.metadata = JSON_SET(
      COALESCE(environment.metadata, JSON_OBJECT()),
      '$.hidden_from_onboarding', JSON_EXTRACT('true', '$'),
      '$.retirement_reason', 'legacy_packaging_seed'
    ),
    environment.version = environment.version + 1,
    environment.updated_at = UTC_TIMESTAMP(3)
WHERE application.code = 'contract_management'
  AND environment.id = '01J00000000000000000000301'
  AND environment.environment = 'dev'
  AND (
    environment.status <> 'DISABLED'
    OR COALESCE(JSON_UNQUOTE(JSON_EXTRACT(environment.metadata, '$.hidden_from_onboarding')), 'false') <> 'true'
  );

-- The deployment-state row was generated by migration 000067 rather than by an operator.
-- Remove only that untouched backfill row; any later controlled operation is preserved and
-- therefore prevents the physical environment deletion below.
DELETE deployment
FROM subsystem_deployment_state AS deployment
JOIN platform_application_environment AS environment
  ON environment.id = deployment.environment_id
 AND environment.tenant_id = deployment.tenant_id
 AND environment.application_id = deployment.application_id
JOIN platform_application AS application
  ON application.id = environment.application_id
 AND application.tenant_id = environment.tenant_id
WHERE application.code = 'contract_management'
  AND environment.id = '01J00000000000000000000301'
  AND environment.environment = 'dev'
  AND deployment.operation = 'MIGRATION_BACKFILL'
  AND deployment.status = 'READY';

-- Remove the seeded login target only when the environment has no durable evidence. Existing
-- installations which really used dev keep a disabled, hidden record instead of losing data.
DELETE target
FROM platform_application_login_target AS target
JOIN platform_application_environment AS environment
  ON environment.id = target.environment_id
JOIN platform_application AS application
  ON application.id = environment.application_id
 AND application.tenant_id = environment.tenant_id
WHERE application.code = 'contract_management'
  AND environment.id = '01J00000000000000000000301'
  AND environment.environment = 'dev'
  AND target.id = '01J00000000000000000000302'
  AND NOT EXISTS (SELECT 1 FROM platform_oauth_client AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM cfg_namespace AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM audit_event AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM audit_ingestion_receipt AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM subsystem_deployment_state AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM subsystem_service_instance AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_application_client_mapping AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_switch_readiness AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_broker_login_verification AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_cutover_lifecycle AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_cutover_timeline_event AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_authorization_projection AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_authorization_outbox AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_authorization_reconcile_backfill AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_authorization_outbox_expansion AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM platform_public_transport_resource AS item WHERE item.environment_id = environment.id);

DELETE environment
FROM platform_application_environment AS environment
JOIN platform_application AS application
  ON application.id = environment.application_id
 AND application.tenant_id = environment.tenant_id
WHERE application.code = 'contract_management'
  AND environment.id = '01J00000000000000000000301'
  AND environment.environment = 'dev'
  AND NOT EXISTS (SELECT 1 FROM platform_application_login_target AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM platform_oauth_client AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM cfg_namespace AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM audit_event AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM audit_ingestion_receipt AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM subsystem_deployment_state AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM subsystem_service_instance AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_application_client_mapping AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_switch_readiness AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_broker_login_verification AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_cutover_lifecycle AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_cutover_timeline_event AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_authorization_projection AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_authorization_outbox AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_authorization_reconcile_backfill AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM keycloak_authorization_outbox_expansion AS item WHERE item.environment_id = environment.id)
  AND NOT EXISTS (SELECT 1 FROM platform_public_transport_resource AS item WHERE item.environment_id = environment.id);
