CREATE TABLE IF NOT EXISTS audit_event_dedup (
    application_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    event_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    audit_row_id BIGINT UNSIGNED NULL,
    occurred_month INT UNSIGNED NOT NULL,
    received_at DATETIME(3) NOT NULL,
    PRIMARY KEY (application_id, event_id),
    KEY idx_audit_dedup_row (audit_row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    occurred_month INT UNSIGNED NOT NULL,
    event_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    application_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    environment_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_instance VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    event_category VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    received_at DATETIME(3) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    actor_name_snapshot VARCHAR(128) NULL,
    session_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    client_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    action VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    resource_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    resource_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    resource_name_snapshot VARCHAR(255) NULL,
    business_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    trace_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_ip VARBINARY(16) NULL,
    user_agent VARCHAR(1000) NULL,
    result VARCHAR(32) NOT NULL,
    reason_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    risk_level VARCHAR(16) NOT NULL,
    classification VARCHAR(32) NOT NULL,
    summary VARCHAR(1000) NULL,
    metadata JSON NULL,
    changes JSON NULL,
    payload_hash BINARY(32) NOT NULL,
    PRIMARY KEY (id, occurred_month),
    KEY idx_audit_app_time (application_id, occurred_at, id),
    KEY idx_audit_tenant_actor_time (tenant_id, actor_id, occurred_at, id),
    KEY idx_audit_resource_time (application_id, resource_type, resource_id, occurred_at),
    KEY idx_audit_trace (trace_id),
    KEY idx_audit_result_risk_time (result, risk_level, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
