CREATE TABLE IF NOT EXISTS iam_user (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    employee_no VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    display_name VARCHAR(128) NOT NULL,
    legal_name VARCHAR(128) NULL,
    email VARCHAR(320) NULL,
    mobile_ciphertext VARBINARY(512) NULL,
    mobile_hash BINARY(32) NULL,
    avatar_file_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    primary_org_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    manager_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    employment_status VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_employee_no (tenant_id, employee_no),
    KEY idx_user_tenant_status (tenant_id, status),
    KEY idx_user_manager (tenant_id, manager_user_id),
    CONSTRAINT fk_user_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS iam_account (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    username VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    account_type VARCHAR(32) NOT NULL,
    auth_source VARCHAR(32) NOT NULL,
    locked_until DATETIME(3) NULL,
    last_login_at DATETIME(3) NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_account_username (tenant_id, username),
    KEY idx_account_user (tenant_id, user_id),
    KEY idx_account_status (tenant_id, status),
    CONSTRAINT fk_account_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES iam_user (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS iam_password_credential (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    account_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    password_hash VARBINARY(255) NOT NULL,
    hash_algorithm VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    algorithm_params JSON NOT NULL,
    password_changed_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NULL,
    must_change TINYINT(1) NOT NULL DEFAULT 0,
    failed_attempts INT UNSIGNED NOT NULL DEFAULT 0,
    last_failed_at DATETIME(3) NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_password_credential_account (account_id),
    CONSTRAINT fk_password_credential_account FOREIGN KEY (account_id) REFERENCES iam_account (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS iam_session (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    account_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    oauth_client_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    refresh_token_hash BINARY(32) NULL,
    token_family_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    device_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    device_name VARCHAR(255) NULL,
    ip_address VARBINARY(16) NULL,
    user_agent VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    revoke_reason VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    status VARCHAR(32) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_session_account (tenant_id, account_id, status, expires_at),
    KEY idx_session_family (token_family_id),
    KEY idx_session_expire (status, expires_at),
    CONSTRAINT fk_session_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_session_account FOREIGN KEY (account_id) REFERENCES iam_account (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
