CREATE TABLE IF NOT EXISTS async_job (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    application_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    job_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    aggregate_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    aggregate_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    payload JSON NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    available_at DATETIME(3) NOT NULL,
    locked_by VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    locked_at DATETIME(3) NULL,
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
    last_error_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    last_error_message VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    KEY idx_job_poll (status, available_at, priority, id),
    KEY idx_job_lock (status, locked_at),
    KEY idx_job_aggregate (aggregate_type, aggregate_id),
    CONSTRAINT fk_async_job_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenant (id) ON DELETE RESTRICT,
    CONSTRAINT fk_async_job_application FOREIGN KEY (application_id) REFERENCES platform_application (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
