package identityhttp

import (
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/J-S-Te/Basic-Platform/backend/internal/platform/identity/application"
	"github.com/J-S-Te/Basic-Platform/backend/internal/platform/identity/domain"
	"github.com/J-S-Te/Basic-Platform/backend/internal/shared/authctx"
	"github.com/J-S-Te/Basic-Platform/backend/internal/shared/httperror"
	"github.com/J-S-Te/Basic-Platform/backend/internal/shared/httpresponse"
)

const maxManagementRequestBytes = 64 << 10

// ManagementHandler is the HTTP adapter for P0 IAM user, account and organization operations.
type ManagementHandler struct {
	service managementApplicationService
	logger  *slog.Logger
}

type managementApplicationService interface {
	ListUsers(context.Context, string, application.PageRequest) (application.PageResult[application.UserView], error)
	CreateUser(context.Context, application.UserCreateInput) (application.UserView, error)
	CreateUsersBatch(context.Context, application.UserBatchCreateInput) ([]application.UserView, error)
	GetUser(context.Context, string, string) (application.UserView, error)
	UpdateUser(context.Context, application.UserUpdateInput) (application.UserView, error)
	DeleteUser(context.Context, application.UserDeleteInput) error
	ListAccounts(context.Context, string, application.PageRequest) (application.PageResult[domain.Account], error)
	UpdateAccount(context.Context, application.AccountUpdateInput) (domain.Account, error)
	ListOrgUnits(context.Context, string, application.PageRequest) (application.PageResult[domain.OrgUnit], error)
	CreateOrgUnit(context.Context, application.OrgUnitCreateInput) (domain.OrgUnit, error)
	ListPositions(context.Context, string, application.PageRequest) (application.PageResult[domain.Position], error)
	CreatePosition(context.Context, application.PositionCreateInput) (domain.Position, error)
	ListMemberships(context.Context, string, application.PageRequest) (application.PageResult[domain.Membership], error)
	CreateMembership(context.Context, application.MembershipCreateInput) (domain.Membership, error)
	UpdateMembership(context.Context, application.MembershipUpdateInput) (domain.Membership, error)
}

// NewManagementHandler constructs an IAM management HTTP adapter.
func NewManagementHandler(service managementApplicationService, logger *slog.Logger) (*ManagementHandler, error) {
	if service == nil || logger == nil {
		return nil, errors.New("identity management handler dependencies must not be nil")
	}
	return &ManagementHandler{service: service, logger: logger}, nil
}

// userCreateRequest intentionally excludes employee_no and version. Employee numbers are
// generated by the backend and optimistic-lock versions only apply to updates.
type userCreateRequest struct {
	DisplayName string  `json:"display_name"`
	Email       *string `json:"email"`
	Mobile      *string `json:"mobile"`
	Status      *string `json:"status"`
}

type userRequest struct {
	DisplayName string  `json:"display_name"`
	EmployeeNo  *string `json:"employee_no"`
	Email       *string `json:"email"`
	Mobile      *string `json:"mobile"`
	Status      *string `json:"status"`
	Version     uint64  `json:"version"`
}

type userBatchCreateRequest struct {
	Items []userCreateRequest `json:"items"`
}

type userBatchCreateResponse struct {
	Items []userResponse `json:"items"`
	Total int            `json:"total"`
}

type userDeleteRequest struct {
	Version uint64 `json:"version"`
}

type accountUpdateRequest struct {
	Status  string `json:"status"`
	Version uint64 `json:"version"`
}

// orgUnitCreateRequest intentionally does not require an organization code. Code remains as an
// ignored compatibility field so a rolling deployment with an older frontend does not fail strict
// JSON decoding; the application service always generates and returns the authoritative code.
type orgUnitCreateRequest struct {
	ParentID  *string `json:"parent_id"`
	Code      *string `json:"code,omitempty"`
	Name      string  `json:"name"`
	SortOrder int     `json:"sort_order"`
}

// positionCreateRequest keeps code as an ignored compatibility field for rolling deployments.
// The backend always returns the authoritative POS-<ULID> code.
type positionCreateRequest struct {
	OrgUnitID string  `json:"org_unit_id"`
	Code      *string `json:"code,omitempty"`
	Name      string  `json:"name"`
}
type membershipRequest struct {
	UserID         string  `json:"user_id"`
	OrgUnitID      string  `json:"org_unit_id"`
	PositionID     string  `json:"position_id"`
	MembershipType string  `json:"membership_type"`
	EffectiveFrom  *string `json:"effective_from"`
	EffectiveTo    *string `json:"effective_to"`
	Status         *string `json:"status"`
	Version        uint64  `json:"version"`
}

type referenceResponse struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
type userResponse struct {
	UserID       string    `json:"user_id"`
	DisplayName  string    `json:"display_name"`
	EmployeeNo   *string   `json:"employee_no,omitempty"`
	Email        *string   `json:"email,omitempty"`
	MobileMasked *string   `json:"mobile_masked,omitempty"`
	Status       string    `json:"status"`
	Version      uint64    `json:"version"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
type accountResponse struct {
	AccountID   string     `json:"account_id"`
	UserID      *string    `json:"user_id,omitempty"`
	AccountName string     `json:"account_name"`
	AccountType string     `json:"account_type"`
	AuthSource  string     `json:"auth_source"`
	Status      string     `json:"status"`
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	Version     uint64     `json:"version"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}
type orgUnitResponse struct {
	OrgUnitID string  `json:"org_unit_id"`
	ParentID  *string `json:"parent_id,omitempty"`
	Code      string  `json:"code"`
	Name      string  `json:"name"`
	SortOrder int     `json:"sort_order"`
	Status    string  `json:"status"`
	Version   uint64  `json:"version"`
}
type positionResponse struct {
	PositionID string `json:"position_id"`
	OrgUnitID  string `json:"org_unit_id"`
	Code       string `json:"code"`
	Name       string `json:"name"`
	Status     string `json:"status"`
	Version    uint64 `json:"version"`
}
type membershipResponse struct {
	MembershipID   string            `json:"membership_id"`
	User           referenceResponse `json:"user"`
	OrgUnit        referenceResponse `json:"org_unit"`
	Position       referenceResponse `json:"position"`
	MembershipType string            `json:"membership_type"`
	EffectiveFrom  *string           `json:"effective_from,omitempty"`
	EffectiveTo    *string           `json:"effective_to,omitempty"`
	Status         string            `json:"status"`
	Version        uint64            `json:"version"`
}
type pageResponse[T any] struct {
	Items    []T   `json:"items"`
	Page     int   `json:"page"`
	PageSize int   `json:"page_size"`
	Total    int64 `json:"total"`
}

func (handler *ManagementHandler) ListUsers(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	query, err := parsePageRequest(request)
	if err != nil {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.ListUsers(request.Context(), principal.Tenant.ID, query)
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	items := make([]userResponse, 0, len(result.Items))
	for _, item := range result.Items {
		items = append(items, toUserResponse(item))
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "操作成功", pageResponse[userResponse]{Items: items, Page: result.Page, PageSize: result.PageSize, Total: result.Total})
}

func (handler *ManagementHandler) CreateUser(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	var payload userCreateRequest
	if !decodeManagementRequest(writer, request, &payload) {
		handler.validation(writer, request)
		return
	}
	status := domain.StatusActive
	if payload.Status != nil {
		status = *payload.Status
	}
	result, err := handler.service.CreateUser(request.Context(), application.UserCreateInput{TenantID: principal.Tenant.ID, OperatorID: principal.User.ID, DisplayName: payload.DisplayName, Email: payload.Email, Mobile: payload.Mobile, Status: status})
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	httpresponse.WriteSuccess(writer, request, http.StatusCreated, "用户已创建", toUserResponse(result))
}

// CreateUsersBatch creates up to one hundred ordinary users atomically. Employee numbers and the
// baseline role assignment are controlled by the application service rather than request input.
func (handler *ManagementHandler) CreateUsersBatch(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	var payload userBatchCreateRequest
	if !decodeManagementRequest(writer, request, &payload) {
		handler.validation(writer, request)
		return
	}
	items := make([]application.UserCreateInput, 0, len(payload.Items))
	for _, item := range payload.Items {
		status := domain.StatusActive
		if item.Status != nil {
			status = *item.Status
		}
		items = append(items, application.UserCreateInput{
			DisplayName: item.DisplayName, Email: item.Email, Mobile: item.Mobile, Status: status,
		})
	}
	result, err := handler.service.CreateUsersBatch(request.Context(), application.UserBatchCreateInput{
		TenantID: principal.Tenant.ID, OperatorID: principal.User.ID, Items: items,
	})
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	responses := make([]userResponse, 0, len(result))
	for _, item := range result {
		responses = append(responses, toUserResponse(item))
	}
	httpresponse.WriteSuccess(writer, request, http.StatusCreated, "用户已批量创建", userBatchCreateResponse{Items: responses, Total: len(responses)})
}

func (handler *ManagementHandler) GetUser(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	result, err := handler.service.GetUser(request.Context(), principal.Tenant.ID, request.PathValue("user_id"))
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "操作成功", toUserResponse(result))
}

func (handler *ManagementHandler) UpdateUser(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	var payload userRequest
	if !decodeManagementRequest(writer, request, &payload) {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.UpdateUser(request.Context(), application.UserUpdateInput{TenantID: principal.Tenant.ID, OperatorID: principal.User.ID, UserID: request.PathValue("user_id"), DisplayName: payload.DisplayName, EmployeeNo: payload.EmployeeNo, Email: payload.Email, Mobile: payload.Mobile, Status: payload.Status, Version: payload.Version, UpdateMobile: payload.Mobile != nil})
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "用户已更新", toUserResponse(result))
}

// DeleteUser logically removes a user and disables all login paths associated with it.
func (handler *ManagementHandler) DeleteUser(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	var payload userDeleteRequest
	if !decodeManagementRequest(writer, request, &payload) {
		handler.validation(writer, request)
		return
	}
	if err := handler.service.DeleteUser(request.Context(), application.UserDeleteInput{
		TenantID: principal.Tenant.ID, OperatorID: principal.User.ID, UserID: request.PathValue("user_id"), Version: payload.Version,
	}); err != nil {
		handler.writeError(writer, request, err)
		return
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "用户已删除", map[string]any{})
}

func (handler *ManagementHandler) ListAccounts(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	query, err := parsePageRequest(request)
	if err != nil {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.ListAccounts(request.Context(), principal.Tenant.ID, query)
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	items := make([]accountResponse, 0, len(result.Items))
	for _, item := range result.Items {
		items = append(items, toAccountResponse(item))
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "操作成功", pageResponse[accountResponse]{Items: items, Page: result.Page, PageSize: result.PageSize, Total: result.Total})
}

func (handler *ManagementHandler) UpdateAccount(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	var payload accountUpdateRequest
	if !decodeManagementRequest(writer, request, &payload) {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.UpdateAccount(request.Context(), application.AccountUpdateInput{TenantID: principal.Tenant.ID, OperatorID: principal.User.ID, AccountID: request.PathValue("account_id"), Status: payload.Status, Version: payload.Version})
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "账号已更新", toAccountResponse(result))
}

func (handler *ManagementHandler) ListOrgUnits(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	query, err := parsePageRequest(request)
	if err != nil {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.ListOrgUnits(request.Context(), principal.Tenant.ID, query)
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	items := make([]orgUnitResponse, 0, len(result.Items))
	for _, item := range result.Items {
		items = append(items, toOrgUnitResponse(item))
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "操作成功", pageResponse[orgUnitResponse]{Items: items, Page: result.Page, PageSize: result.PageSize, Total: result.Total})
}

func (handler *ManagementHandler) CreateOrgUnit(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	var payload orgUnitCreateRequest
	if !decodeManagementRequest(writer, request, &payload) {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.CreateOrgUnit(request.Context(), application.OrgUnitCreateInput{TenantID: principal.Tenant.ID, OperatorID: principal.User.ID, ParentID: payload.ParentID, Name: payload.Name, SortOrder: payload.SortOrder})
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	httpresponse.WriteSuccess(writer, request, http.StatusCreated, "组织单元已创建", toOrgUnitResponse(result))
}

func (handler *ManagementHandler) ListPositions(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	query, err := parsePageRequest(request)
	if err != nil {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.ListPositions(request.Context(), principal.Tenant.ID, query)
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	items := make([]positionResponse, 0, len(result.Items))
	for _, item := range result.Items {
		items = append(items, toPositionResponse(item))
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "操作成功", pageResponse[positionResponse]{Items: items, Page: result.Page, PageSize: result.PageSize, Total: result.Total})
}

func (handler *ManagementHandler) CreatePosition(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	var payload positionCreateRequest
	if !decodeManagementRequest(writer, request, &payload) {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.CreatePosition(request.Context(), application.PositionCreateInput{TenantID: principal.Tenant.ID, OperatorID: principal.User.ID, OrgUnitID: payload.OrgUnitID, Name: payload.Name})
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	httpresponse.WriteSuccess(writer, request, http.StatusCreated, "岗位已创建", toPositionResponse(result))
}

func (handler *ManagementHandler) ListMemberships(writer http.ResponseWriter, request *http.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	query, err := parsePageRequest(request)
	if err != nil {
		handler.validation(writer, request)
		return
	}
	result, err := handler.service.ListMemberships(request.Context(), principal.Tenant.ID, query)
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	items := make([]membershipResponse, 0, len(result.Items))
	for _, item := range result.Items {
		items = append(items, toMembershipResponse(item))
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "操作成功", pageResponse[membershipResponse]{Items: items, Page: result.Page, PageSize: result.PageSize, Total: result.Total})
}

func (handler *ManagementHandler) CreateMembership(writer http.ResponseWriter, request *http.Request) {
	handler.writeMembership(writer, request, false)
}
func (handler *ManagementHandler) UpdateMembership(writer http.ResponseWriter, request *http.Request) {
	handler.writeMembership(writer, request, true)
}

func (handler *ManagementHandler) writeMembership(writer http.ResponseWriter, request *http.Request, update bool) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok {
		handler.unauthenticated(writer, request)
		return
	}
	var payload membershipRequest
	if !decodeManagementRequest(writer, request, &payload) {
		handler.validation(writer, request)
		return
	}
	from, err := parseDate(payload.EffectiveFrom)
	if err != nil {
		handler.validation(writer, request)
		return
	}
	to, err := parseDate(payload.EffectiveTo)
	if err != nil {
		handler.validation(writer, request)
		return
	}
	input := application.MembershipCreateInput{TenantID: principal.Tenant.ID, OperatorID: principal.User.ID, UserID: payload.UserID, OrgUnitID: payload.OrgUnitID, PositionID: payload.PositionID, MembershipType: payload.MembershipType, EffectiveFrom: from, EffectiveTo: to}
	if !update {
		result, err := handler.service.CreateMembership(request.Context(), input)
		if err != nil {
			handler.writeError(writer, request, err)
			return
		}
		httpresponse.WriteSuccess(writer, request, http.StatusCreated, "任职已创建", toMembershipResponse(result))
		return
	}
	result, err := handler.service.UpdateMembership(request.Context(), application.MembershipUpdateInput{MembershipCreateInput: input, MembershipID: request.PathValue("membership_id"), Status: payload.Status, Version: payload.Version})
	if err != nil {
		handler.writeError(writer, request, err)
		return
	}
	httpresponse.WriteSuccess(writer, request, http.StatusOK, "任职已更新", toMembershipResponse(result))
}

func (handler *ManagementHandler) writeError(writer http.ResponseWriter, request *http.Request, err error) {
	switch {
	case errors.Is(err, application.ErrValidation):
		handler.validation(writer, request)
	case errors.Is(err, application.ErrNotFound):
		httpresponse.WriteError(writer, request, http.StatusNotFound, httperror.NotFound)
	case errors.Is(err, application.ErrConflict):
		httpresponse.WriteError(writer, request, http.StatusConflict, httperror.Conflict)
	case errors.Is(err, application.ErrVersionConflict):
		httpresponse.WriteError(writer, request, http.StatusConflict, httperror.VersionConflict)
	default:
		handler.logger.Error("identity management request failed", "error", err)
		httpresponse.WriteError(writer, request, http.StatusInternalServerError, httperror.Internal)
	}
}
func (handler *ManagementHandler) validation(w http.ResponseWriter, r *http.Request) {
	httpresponse.WriteError(w, r, http.StatusUnprocessableEntity, httperror.Validation)
}
func (handler *ManagementHandler) unauthenticated(w http.ResponseWriter, r *http.Request) {
	httpresponse.WriteError(w, r, http.StatusUnauthorized, httperror.Unauthenticated)
}

func decodeManagementRequest(writer http.ResponseWriter, request *http.Request, destination any) bool {
	defer request.Body.Close()
	decoder := json.NewDecoder(http.MaxBytesReader(writer, request.Body, maxManagementRequestBytes))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil {
		return false
	}
	return ensureSingleJSONValue(decoder) == nil
}
func parsePageRequest(request *http.Request) (application.PageRequest, error) {
	query := request.URL.Query()
	page, err := positiveQuery(query.Get("page"), 1)
	if err != nil {
		return application.PageRequest{}, err
	}
	pageSize, err := positiveQuery(query.Get("page_size"), 20)
	if err != nil || pageSize > 100 {
		return application.PageRequest{}, errors.New("invalid page size")
	}
	status := strings.TrimSpace(query.Get("filter[status]"))
	if status != "" && status != domain.StatusActive && status != domain.StatusDisabled {
		return application.PageRequest{}, errors.New("invalid status")
	}
	return application.PageRequest{Page: page, PageSize: pageSize, Keyword: strings.TrimSpace(query.Get("keyword")), Status: status}, nil
}
func positiveQuery(value string, fallback int) (int, error) {
	if value == "" {
		return fallback, nil
	}
	parsed, err := strconv.Atoi(value)
	if err != nil || parsed < 1 {
		return 0, errors.New("invalid positive query")
	}
	return parsed, nil
}
func parseDate(value *string) (*time.Time, error) {
	if value == nil || *value == "" {
		return nil, nil
	}
	parsed, err := time.Parse("2006-01-02", *value)
	if err != nil {
		return nil, err
	}
	parsed = parsed.UTC()
	return &parsed, nil
}
func dateString(value *time.Time) *string {
	if value == nil {
		return nil
	}
	formatted := value.UTC().Format("2006-01-02")
	return &formatted
}
func toUserResponse(value application.UserView) userResponse {
	return userResponse{UserID: value.ID, DisplayName: value.DisplayName, EmployeeNo: value.EmployeeNo, Email: value.Email, MobileMasked: value.MobileMasked, Status: value.Status, Version: value.Version, CreatedAt: value.CreatedAt, UpdatedAt: value.UpdatedAt}
}
func toAccountResponse(value domain.Account) accountResponse {
	return accountResponse{AccountID: value.ID, UserID: value.UserID, AccountName: value.AccountName, AccountType: value.AccountType, AuthSource: value.AuthSource, Status: value.Status, LastLoginAt: value.LastLoginAt, Version: value.Version, CreatedAt: value.CreatedAt, UpdatedAt: value.UpdatedAt}
}
func toOrgUnitResponse(value domain.OrgUnit) orgUnitResponse {
	return orgUnitResponse{OrgUnitID: value.ID, ParentID: value.ParentID, Code: value.Code, Name: value.Name, SortOrder: value.SortOrder, Status: value.Status, Version: value.Version}
}
func toPositionResponse(value domain.Position) positionResponse {
	return positionResponse{PositionID: value.ID, OrgUnitID: value.OrgUnitID, Code: value.Code, Name: value.Name, Status: value.Status, Version: value.Version}
}
func toMembershipResponse(value domain.Membership) membershipResponse {
	return membershipResponse{MembershipID: value.ID, User: referenceResponse{ID: value.User.ID, Name: value.User.Name}, OrgUnit: referenceResponse{ID: value.OrgUnit.ID, Name: value.OrgUnit.Name}, Position: referenceResponse{ID: value.Position.ID, Name: value.Position.Name}, MembershipType: value.MembershipType, EffectiveFrom: dateString(value.EffectiveFrom), EffectiveTo: dateString(value.EffectiveTo), Status: value.Status, Version: value.Version}
}
