<script setup>
import { onMounted, ref } from 'vue'
import { getNotification, getUnreadCount, listInbox, markAllNotificationsRead, markNotificationRead } from '@/modules/platform/notifications/api/notifications'
import '@/modules/platform/notifications/styles/notification-center.css'
const emit = defineEmits(['toast']); const items = ref([]); const unreadCount = ref(0); const loading = ref(false); const detail = ref(null); const error = ref('')
async function refresh() { loading.value = true; error.value = ''; try { const [inbox, unread] = await Promise.all([listInbox(), getUnreadCount()]); items.value = inbox.items || []; unreadCount.value = unread.unread_count || 0 } catch (e) { error.value = e.message } finally { loading.value = false } }
async function open(item) { try { detail.value = await getNotification(item.delivery_id); if (!detail.value.read_at) { detail.value = await markNotificationRead(item.delivery_id); unreadCount.value = Math.max(0, unreadCount.value - 1); const current = items.value.find((value) => value.delivery_id === item.delivery_id); if (current) current.read_at = detail.value.read_at } } catch (e) { emit('toast', e.message) } }
async function readAll() { try { await markAllNotificationsRead(); items.value.forEach((item) => { item.read_at = new Date().toISOString() }); unreadCount.value = 0; emit('toast', '全部站内信已标记为已读。') } catch (e) { emit('toast', e.message) } }
onMounted(refresh)
</script>
<template><section class="notification-center"><header class="notification-center-head"><div><span class="notification-kicker">IN-APP NOTIFICATIONS</span><h2>通知中心 <b v-if="unreadCount">{{ unreadCount }}</b></h2><p>仅展示当前登录用户可见的站内信；打开关联业务前仍由目标系统重新授权。</p></div><div><button class="console-button ghost" type="button" :disabled="loading" @click="refresh">刷新</button><button class="console-button primary" type="button" :disabled="!unreadCount" @click="readAll">全部已读</button></div></header><p v-if="error" class="notification-error">{{ error }}</p><div v-if="loading" class="notification-empty">正在加载站内信…</div><div v-else-if="!items.length" class="notification-empty">暂无站内信。</div><div v-else class="notification-list"><button v-for="item in items" :key="item.delivery_id" class="notification-item" :class="{ unread: !item.read_at }" type="button" @click="open(item)"><span class="notification-dot" /><span><small>{{ item.category }}</small><strong>{{ item.title }}</strong><p>{{ item.content }}</p><time>{{ item.delivered_at }}</time></span></button></div><aside v-if="detail" class="notification-detail"><header><h3>{{ detail.title }}</h3><button type="button" aria-label="关闭" @click="detail = null">×</button></header><p>{{ detail.content }}</p><a v-if="detail.target_url" :href="detail.target_url">查看关联内容</a></aside></section></template>
