package http

import (
	"context"
	stdhttp "net/http"
	"net/http/httputil"
	"net/url"
	"strings"

	"github.com/J-S-Te/Basic-Platform/internal/platform/applicationregistry/application"
	"github.com/J-S-Te/Basic-Platform/internal/shared/authctx"
	"github.com/J-S-Te/Basic-Platform/internal/shared/httperror"
	"github.com/J-S-Te/Basic-Platform/internal/shared/httpresponse"
)

type subsystemServiceRouteReader interface {
	ListSubsystemServiceInstances(context.Context, string, string, string) ([]application.SubsystemServiceInstance, error)
}

// SubsystemServiceRouteHandler exposes a read-only, tenant-scoped route lookup for the portal
// gateway. The response is derived from current discovery rows; no Nginx include or host file is
// generated by this endpoint.
type SubsystemServiceRouteHandler struct {
	reader subsystemServiceRouteReader
}

func NewSubsystemServiceRouteHandler(reader subsystemServiceRouteReader) (*SubsystemServiceRouteHandler, error) {
	if reader == nil {
		return nil, application.ErrValidation
	}
	return &SubsystemServiceRouteHandler{reader: reader}, nil
}

type subsystemServiceRouteResponse struct {
	ApplicationCode string `json:"application_code"`
	Environment     string `json:"environment"`
	ServiceName     string `json:"service_name"`
	ServiceRole     string `json:"service_role"`
	Protocol        string `json:"protocol"`
	UpstreamURL     string `json:"upstream_url"`
	PathPrefix      string `json:"path_prefix,omitempty"`
	HealthEndpoint  string `json:"health_endpoint,omitempty"`
	Version         string `json:"version,omitempty"`
	Status          string `json:"status"`
}

func (handler *SubsystemServiceRouteHandler) Resolve(writer stdhttp.ResponseWriter, request *stdhttp.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok || strings.TrimSpace(principal.Tenant.ID) == "" {
		httpresponse.WriteError(writer, request, stdhttp.StatusUnauthorized, httperror.Unauthenticated)
		return
	}
	query := request.URL.Query()
	applicationCode := strings.TrimSpace(query.Get("application_code"))
	environment := strings.TrimSpace(query.Get("environment"))
	role := strings.TrimSpace(query.Get("service_role"))
	if applicationCode == "" || environment == "" || role == "" {
		httpresponse.WriteError(writer, request, stdhttp.StatusBadRequest, httperror.Validation)
		return
	}
	instances, err := handler.reader.ListSubsystemServiceInstances(request.Context(), principal.Tenant.ID, applicationCode, environment)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusInternalServerError, httperror.Internal)
		return
	}
	instance, err := application.SelectSubsystemServiceRoute(instances, role)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	upstreamURL, err := instance.UpstreamURL()
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	httpresponse.WriteSuccess(writer, request, stdhttp.StatusOK, "子系统服务路由查询成功", subsystemServiceRouteResponse{
		ApplicationCode: instance.ApplicationCode, Environment: instance.Environment, ServiceName: instance.ServiceName,
		ServiceRole: instance.ServiceRole, Protocol: instance.Protocol, UpstreamURL: upstreamURL,
		PathPrefix: instance.PathPrefix, HealthEndpoint: instance.HealthEndpoint, Version: instance.Version, Status: instance.Status,
	})
}

// Proxy forwards a request to the currently healthy discovered instance. It is intentionally
// mounted under the authenticated API namespace; the public portal can adopt it incrementally
// without generating an Nginx location file.
func (handler *SubsystemServiceRouteHandler) Proxy(writer stdhttp.ResponseWriter, request *stdhttp.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok || strings.TrimSpace(principal.Tenant.ID) == "" {
		httpresponse.WriteError(writer, request, stdhttp.StatusUnauthorized, httperror.Unauthenticated)
		return
	}
	query := request.URL.Query()
	applicationCode := strings.TrimSpace(request.PathValue("application_code"))
	environment := strings.TrimSpace(query.Get("environment"))
	role := strings.TrimSpace(query.Get("service_role"))
	if applicationCode == "" || environment == "" || role == "" {
		httpresponse.WriteError(writer, request, stdhttp.StatusBadRequest, httperror.Validation)
		return
	}
	instances, err := handler.reader.ListSubsystemServiceInstances(request.Context(), principal.Tenant.ID, applicationCode, environment)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusInternalServerError, httperror.Internal)
		return
	}
	instance, err := application.SelectSubsystemServiceRoute(instances, role)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	upstream, err := instance.UpstreamURL()
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	target, err := url.Parse(upstream)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	proxy := httputil.NewSingleHostReverseProxy(target)
	originalDirector := proxy.Director
	proxy.Director = func(outgoing *stdhttp.Request) {
		originalDirector(outgoing)
		forwardPath := request.PathValue("path")
		if forwardPath == "" {
			forwardPath = "/"
		}
		if !strings.HasPrefix(forwardPath, "/") {
			forwardPath = "/" + forwardPath
		}
		outgoing.URL.Path = forwardPath
		outgoing.URL.RawPath = ""
		outgoing.Host = target.Host
	}
	proxy.ErrorHandler = func(stdhttp.ResponseWriter, *stdhttp.Request, error) {
		httpresponse.WriteError(writer, request, stdhttp.StatusBadGateway, httperror.DependencyUnavailable)
	}
	proxy.ServeHTTP(writer, request)
}
