package http

import (
	"context"
	stdhttp "net/http"
	"net/http/httputil"
	"net/url"
	"strings"

	"github.com/J-S-Te/Basic-Platform/internal/platform/applicationregistry/application"
	"github.com/J-S-Te/Basic-Platform/internal/shared/authctx"
	"github.com/J-S-Te/Basic-Platform/internal/shared/httperror"
	"github.com/J-S-Te/Basic-Platform/internal/shared/httpresponse"
)

type subsystemServiceRouteReader interface {
	ListSubsystemServiceInstances(context.Context, string, string, string) ([]application.SubsystemServiceInstance, error)
}

// subsystemAccessChecker 复核调用者是否在目标应用上存在应用授权。平台级
// platform:application:read 权限只能证明"能看目录"，不能证明"有权使用该子系统"。
type subsystemAccessChecker interface {
	HasApplicationGrant(context.Context, string, string, string) (bool, error)
}

// SubsystemServiceRouteHandler exposes a read-only, tenant-scoped route lookup for the portal
// gateway. The response is derived from current discovery rows; no Nginx include or host file is
// generated by this endpoint.
type SubsystemServiceRouteHandler struct {
	reader     subsystemServiceRouteReader
	authorizer subsystemAccessChecker
}

func NewSubsystemServiceRouteHandler(reader subsystemServiceRouteReader, authorizers ...subsystemAccessChecker) (*SubsystemServiceRouteHandler, error) {
	if reader == nil {
		return nil, application.ErrValidation
	}
	handler := &SubsystemServiceRouteHandler{reader: reader}
	if len(authorizers) > 1 {
		return nil, application.ErrValidation
	}
	if len(authorizers) == 1 && authorizers[0] != nil {
		handler.authorizer = authorizers[0]
	}
	return handler, nil
}

type subsystemServiceRouteResponse struct {
	ApplicationCode string `json:"application_code"`
	Environment     string `json:"environment"`
	ServiceName     string `json:"service_name"`
	ServiceRole     string `json:"service_role"`
	Protocol        string `json:"protocol"`
	UpstreamURL     string `json:"upstream_url"`
	PathPrefix      string `json:"path_prefix,omitempty"`
	HealthEndpoint  string `json:"health_endpoint,omitempty"`
	Version         string `json:"version,omitempty"`
	Status          string `json:"status"`
}

// sensitiveSubsystemProxyRequestHeaders 列出不得跨越平台与子系统信任边界的入站请求头。
// 这些值可能承载平台会话、访问令牌、租户身份或可重放的内部调用凭据；子系统如需身份，
// 应通过自己的认证流程获得，不能复用浏览器提交给基础平台的凭据。
var sensitiveSubsystemProxyRequestHeaders = []string{
	"Authorization",
	"Proxy-Authorization",
	"Cookie",
	"X-Access-Token",
	"X-Api-Key",
	"X-Csrf-Token",
	"X-Xsrf-Token",
	"X-Tenant-Id",
	"X-User-Id",
	"X-Authenticated-User",
	"X-Auth-Request-User",
	"X-Auth-Request-Email",
	"X-Auth-Request-Groups",
	"X-Forwarded-Access-Token",
	"X-Forwarded-User",
	"X-Forwarded-Email",
	"X-Forwarded-Groups",
	"X-Forwarded-Preferred-Username",
	"X-Integration-Timestamp",
	"X-Integration-Nonce",
}

func (handler *SubsystemServiceRouteHandler) Resolve(writer stdhttp.ResponseWriter, request *stdhttp.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok || strings.TrimSpace(principal.Tenant.ID) == "" {
		httpresponse.WriteError(writer, request, stdhttp.StatusUnauthorized, httperror.Unauthenticated)
		return
	}
	query := request.URL.Query()
	applicationCode := strings.TrimSpace(query.Get("application_code"))
	environment := strings.TrimSpace(query.Get("environment"))
	role := strings.TrimSpace(query.Get("service_role"))
	if applicationCode == "" || environment == "" || role == "" {
		httpresponse.WriteError(writer, request, stdhttp.StatusBadRequest, httperror.Validation)
		return
	}
	instances, err := handler.reader.ListSubsystemServiceInstances(request.Context(), principal.Tenant.ID, applicationCode, environment)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusInternalServerError, httperror.Internal)
		return
	}
	instance, err := application.SelectSubsystemServiceRoute(instances, role)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	upstreamURL, err := instance.UpstreamURL()
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	httpresponse.WriteSuccess(writer, request, stdhttp.StatusOK, "子系统服务路由查询成功", subsystemServiceRouteResponse{
		ApplicationCode: instance.ApplicationCode, Environment: instance.Environment, ServiceName: instance.ServiceName,
		ServiceRole: instance.ServiceRole, Protocol: instance.Protocol, UpstreamURL: upstreamURL,
		PathPrefix: instance.PathPrefix, HealthEndpoint: instance.HealthEndpoint, Version: instance.Version, Status: instance.Status,
	})
}

// Proxy forwards a request to the currently healthy discovered instance. It is intentionally
// mounted under the authenticated API namespace; the public portal can adopt it incrementally
// without generating an Nginx location file.
func (handler *SubsystemServiceRouteHandler) Proxy(writer stdhttp.ResponseWriter, request *stdhttp.Request) {
	principal, ok := authctx.PrincipalFromContext(request.Context())
	if !ok || strings.TrimSpace(principal.Tenant.ID) == "" {
		httpresponse.WriteError(writer, request, stdhttp.StatusUnauthorized, httperror.Unauthenticated)
		return
	}
	// 反向代理只允许只读方法：写操作必须走子系统自己的会话与授权边界。
	if request.Method != stdhttp.MethodGet && request.Method != stdhttp.MethodHead {
		writer.Header().Set("Allow", "GET, HEAD")
		httpresponse.WriteError(writer, request, stdhttp.StatusMethodNotAllowed, httperror.MethodNotAllowed)
		return
	}
	query := request.URL.Query()
	applicationCode := strings.TrimSpace(request.PathValue("application_code"))
	environment := strings.TrimSpace(query.Get("environment"))
	role := strings.TrimSpace(query.Get("service_role"))
	if applicationCode == "" || environment == "" || role == "" {
		httpresponse.WriteError(writer, request, stdhttp.StatusBadRequest, httperror.Validation)
		return
	}
	// 逐应用授权复核：仅有平台目录读权限不能代理任何子系统流量。
	if handler.authorizer != nil {
		granted, grantErr := handler.authorizer.HasApplicationGrant(request.Context(), principal.Tenant.ID, principal.User.ID, applicationCode)
		if grantErr != nil {
			httpresponse.WriteError(writer, request, stdhttp.StatusInternalServerError, httperror.Internal)
			return
		}
		if !granted {
			httpresponse.WriteError(writer, request, stdhttp.StatusForbidden, httperror.Forbidden)
			return
		}
	}
	instances, err := handler.reader.ListSubsystemServiceInstances(request.Context(), principal.Tenant.ID, applicationCode, environment)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusInternalServerError, httperror.Internal)
		return
	}
	instance, err := application.SelectSubsystemServiceRoute(instances, role)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	upstream, err := instance.UpstreamURL()
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	target, err := url.Parse(upstream)
	if err != nil {
		httpresponse.WriteError(writer, request, stdhttp.StatusServiceUnavailable, httperror.DependencyUnavailable)
		return
	}
	proxy := httputil.NewSingleHostReverseProxy(target)
	originalDirector := proxy.Director
	proxy.Director = func(outgoing *stdhttp.Request) {
		originalDirector(outgoing)
		// NewSingleHostReverseProxy 会复制全部入站请求头；在改写路径前先清除平台侧
		// 身份材料，防止低信任子系统取得平台 Cookie 或 Bearer 令牌后横向调用。
		stripSensitiveSubsystemProxyRequestHeaders(outgoing.Header)
		forwardPath := request.PathValue("path")
		if forwardPath == "" {
			forwardPath = "/"
		}
		if !strings.HasPrefix(forwardPath, "/") {
			forwardPath = "/" + forwardPath
		}
		outgoing.URL.Path = forwardPath
		outgoing.URL.RawPath = ""
		outgoing.Host = target.Host
	}
	proxy.ErrorHandler = func(stdhttp.ResponseWriter, *stdhttp.Request, error) {
		httpresponse.WriteError(writer, request, stdhttp.StatusBadGateway, httperror.DependencyUnavailable)
	}
	proxy.ServeHTTP(writer, request)
}

// stripSensitiveSubsystemProxyRequestHeaders 清除代理请求中的平台凭据和身份断言。
// 参数 header 会原地修改；函数无返回值，未列入敏感清单的内容协商和追踪头保持不变。
func stripSensitiveSubsystemProxyRequestHeaders(header stdhttp.Header) {
	for _, name := range sensitiveSubsystemProxyRequestHeaders {
		header.Del(name)
	}
}
