// Package security contains process-local cryptographic helpers.
package security

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
)

// MobileProtector protects mobile numbers before they are persisted. The ciphertext format is
// nonce || AES-GCM ciphertext; the corresponding SHA-256 digest supports exact matching without
// exposing the original number in a database index.
type MobileProtector struct {
	key []byte
}

// NewMobileProtector creates a protector from a base64-encoded 32-byte AES-256 key. An empty key
// is allowed so development environments that do not collect mobile numbers can still start; an
// attempt to persist a mobile number then fails explicitly instead of storing plaintext.
func NewMobileProtector(encodedKey string) (*MobileProtector, error) {
	if encodedKey == "" {
		return &MobileProtector{}, nil
	}
	key, err := base64.StdEncoding.DecodeString(encodedKey)
	if err != nil {
		return nil, fmt.Errorf("decode IAM_MOBILE_ENCRYPTION_KEY: %w", err)
	}
	if len(key) != 32 {
		return nil, errors.New("IAM_MOBILE_ENCRYPTION_KEY must decode to 32 bytes")
	}
	return &MobileProtector{key: key}, nil
}

// Encrypt encrypts a normalized phone number for storage.
func (protector *MobileProtector) Encrypt(value string) ([]byte, error) {
	gcm, err := protector.gcm()
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("generate mobile encryption nonce: %w", err)
	}
	return gcm.Seal(nonce, nonce, []byte(value), nil), nil
}

// Decrypt reads a ciphertext generated by Encrypt.
func (protector *MobileProtector) Decrypt(ciphertext []byte) (string, error) {
	gcm, err := protector.gcm()
	if err != nil {
		return "", err
	}
	if len(ciphertext) < gcm.NonceSize() {
		return "", errors.New("mobile ciphertext is malformed")
	}
	plaintext, err := gcm.Open(nil, ciphertext[:gcm.NonceSize()], ciphertext[gcm.NonceSize():], nil)
	if err != nil {
		return "", fmt.Errorf("decrypt mobile ciphertext: %w", err)
	}
	return string(plaintext), nil
}

// Digest returns the fixed-width keyed exact-match digest stored in iam_user.mobile_hash.
// The encryption key is deliberately also the HMAC key so a lookup digest cannot be brute-forced
// from the database alone.
func (protector *MobileProtector) Digest(value string) []byte {
	if protector == nil || len(protector.key) == 0 {
		digest := sha256.Sum256([]byte(value))
		return digest[:]
	}
	mac := hmac.New(sha256.New, protector.key)
	_, _ = mac.Write([]byte(value))
	return mac.Sum(nil)
}

func (protector *MobileProtector) gcm() (cipher.AEAD, error) {
	if protector == nil || len(protector.key) != 32 {
		return nil, errors.New("mobile encryption is not configured")
	}
	block, err := aes.NewCipher(protector.key)
	if err != nil {
		return nil, fmt.Errorf("create mobile encryption cipher: %w", err)
	}
	return cipher.NewGCM(block)
}
