// Package security 提供平台模块共享的进程内密码学原语。
package security

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
)

// MobileProtector 把手机号以 nonce || AES-GCM 密文保存，同时生成定长 HMAC 摘要用于精确查询，
// 避免数据库索引直接暴露原值。调用方必须先完成手机号规范化，否则同一号码会得到不同摘要。
type MobileProtector struct {
	key []byte
}

// NewMobileProtector 接受 Base64 编码的 32 字节 AES 密钥。开发环境可不配置以便启动，但真正
// 写入手机号时会明确失败，绝不以明文作为降级路径。
func NewMobileProtector(encodedKey string) (*MobileProtector, error) {
	if encodedKey == "" {
		return &MobileProtector{}, nil
	}
	key, err := base64.StdEncoding.DecodeString(encodedKey)
	if err != nil {
		return nil, fmt.Errorf("decode IAM_MOBILE_ENCRYPTION_KEY: %w", err)
	}
	if len(key) != 32 {
		return nil, errors.New("IAM_MOBILE_ENCRYPTION_KEY must decode to 32 bytes")
	}
	return &MobileProtector{key: key}, nil
}

// Encrypt encrypts a normalized phone number for storage.
func (protector *MobileProtector) Encrypt(value string) ([]byte, error) {
	gcm, err := protector.gcm()
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("generate mobile encryption nonce: %w", err)
	}
	return gcm.Seal(nonce, nonce, []byte(value), nil), nil
}

// Decrypt reads a ciphertext generated by Encrypt.
func (protector *MobileProtector) Decrypt(ciphertext []byte) (string, error) {
	gcm, err := protector.gcm()
	if err != nil {
		return "", err
	}
	if len(ciphertext) < gcm.NonceSize() {
		return "", errors.New("mobile ciphertext is malformed")
	}
	plaintext, err := gcm.Open(nil, ciphertext[:gcm.NonceSize()], ciphertext[gcm.NonceSize():], nil)
	if err != nil {
		return "", fmt.Errorf("decrypt mobile ciphertext: %w", err)
	}
	return string(plaintext), nil
}

// Digest 返回 iam_user.mobile_hash 使用的定长键控摘要。数据库泄露者缺少进程密钥时，
// 不能仅靠低熵手机号字典离线重建索引值。
func (protector *MobileProtector) Digest(value string) []byte {
	if protector == nil || len(protector.key) == 0 {
		digest := sha256.Sum256([]byte(value))
		return digest[:]
	}
	mac := hmac.New(sha256.New, protector.key)
	_, _ = mac.Write([]byte(value))
	return mac.Sum(nil)
}

func (protector *MobileProtector) gcm() (cipher.AEAD, error) {
	if protector == nil || len(protector.key) != 32 {
		return nil, errors.New("mobile encryption is not configured")
	}
	block, err := aes.NewCipher(protector.key)
	if err != nil {
		return nil, fmt.Errorf("create mobile encryption cipher: %w", err)
	}
	return cipher.NewGCM(block)
}
